language: cpp
sudo: false
branches:
  only:
    - dev

env:
  global:
    - TRAVIS_BUILD_TYPE=Debug

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
      sudo: required
      addons:
        apt:
          update: true
          sources:
            - sourceline: ''
          package:
            - libassimp-dev 
            - libglm-dev 
            - libxcb-dri3-0 
            - libxcb-present0 
            - libpciaccess0 
            - cmake 
            - libpng-dev 
            - libxcb-dri3-dev 
            - libx11-dev 
            - libx11-xcb-dev
            - libwayland-dev 
            - libxrandr-dev
      before_script:
        - wget -O vulkan.run https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.1.97.0/linux/vulkansdk-linux-x86_64-1.1.97.0.tar.gz
        - chmod ugo+x vulkan.run
        - ./vulkan.run
    - os: osx
      compiler: clang
      cache:
        ccache: true
        directories:
          - ~/Library/Caches/Homebrew
      addons:
        homebrew:
          update: true
          taps: apenngrace/vulkan
          package:
            - cmake
            - ccache
            - libpng
            - libjpeg-turbo
            - boost
            - vulkan-sdk

before_script:
  - ccache -s 
  - cmake -G "Unix Makefiles"
  - cmake --build . -- -j
  - ccache -s
