language: cpp
sudo: false
branches:
  only:
    - dev

env:
  global:
    - TRAVIS_BUILD_TYPE=Debug

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: 
        - clang 
        - gcc
      sudo: required
      addons:
        apt:
          update: true
          package:
            - libx11-xcb-dev
            - libjpeg-turbo-dev
            - libpng-dev
            - glm
            - cmake
      before_install:
        - apt install lunarg-vulkan-sdk
    - os: osx
      compiler: clang
      cache:
        ccache: true
        directories:
          - ~/Library/Caches/Homebrew
      addons:
        homebrew:
          update: true
          taps: apenngrace/vulkan
          package:
            - cmake
            - ccache
            - libpng
            - libjpeg-turbo
            - boost
            - vulkan-sdk

before_script:
  - ccache -s 
  - cmake -G "Unix Makefiles"
  - cmake --build . -- -j
  - ccache -s
