language: cpp
sudo: false
branches:
  only:
    - dev

env:
  global:
    - TRAVIS_BUILD_TYPE=Debug

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
      sudo: required
      addons:
        apt:
          package:
            - libx11-xcb-dev
            - lunarg-vulkan-sdk
            - libjpeg-turbo-dev
            - libpng-dev
            - glm
            - cmake
    - os: osx
      compiler: clang
      cache:
        ccache: true
        directories:
          - ~/Library/Caches/Homebrew
      before_install:
        - "brew update && brew upgrade && brew install cmake ccache && brew cask install brew cask install apenngrace/vulkan/vulkan-sdk"

before_script:
  - ccache -s 
  - cmake -G "Unix Makefiles"
  - cmake --build . -- -j
  - ccache -s
