language: cpp
branches:
  only:
    - dev

env:
  global:
    - TRAVIS_BUILD_TYPE=Debug

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:xorg-edgers/ppa"
          packages:
            - gcc-7
            - g++-7
            - libassimp-dev 
            - libglm-dev 
            - libxcb-dri3-0 
            - libxcb-present0 
            - libpciaccess0 
            - cmake 
            - libpng-dev 
            - libxcb-dri3-dev 
            - libx11-dev 
            - libx11-xcb-dev
            - libwayland-dev 
            - libxrandr-dev
            - vulkan
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && INFO=linux-C++17-gcc-7-release-xenial
      script:
        - cmake --version
        - mkdir build-linux-C++17-gcc-7-release-xenial
        - cd build-linux-C++17-gcc-7-release-xenial
        - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release ..
        - cmake -E time cmake --build .

before_install:
  - eval "${MATRIX_EVAL}"
