language: cpp
sudo: false
branches:
  only:
    - dev

env:
  global:
    - TRAVIS_BUILD_TYPE=Debug

matrix:
  include:
    - os: linux
      compiler: clang
      sudo: required
    - os: osx
      compiler: clang
      cache:
        ccache: true
        directories:
          - ~/Library/Caches/Homebrew
      before_install:
        - "brew update && brew upgrade && brew install cmake ccache && brew cask install brew cask install apenngrace/vulkan/vulkan-sdk"

