if(WIN32)
	set(OS "Win32")
	set(STORM_OS_WIN32 ON)
elseif(UNIX)
	set(STORM_OS_POSIX ON)
    if(APPLE)
		set(OS "macOS")
		set(STORM_OS_MACOS ON)
		add_compile_options("-fcolor-diagnostics")
    else()
		set(OS "Linux")
	    set(STORM_OS_LINUX ON)
    endif()
else()
    message(FATAL "Unsupported platform")
endif()

string (REGEX MATCH "\\.el[1-9]" os_version_suffix ${CMAKE_SYSTEM})

message("-- OS:               ${OS}")
message("-- SYSTEM_INFO_FILE: ${CMAKE_SYSTEM_INFO_FILE}")
message("-- SYSTEM_NAME:      ${CMAKE_SYSTEM_NAME}")
message("-- SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR}")
message("-- SYSTEM:           ${CMAKE_SYSTEM}")
